# Generated by Django 3.0.5 on 2022-03-13 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('no_of_videos', models.IntegerField(default=0)),
                ('no_of_videos_completed', models.IntegerField(default=0)),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
