# Generated by Django 3.0.5 on 2022-03-13 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_data',
            name='user_id',
        ),
        migrations.AddField(
            model_name='course_data',
            name='user_name',
            field=models.CharField(default='vijayalakshmi', max_length=255),
            preserve_default=False,
        ),
    ]
